import pandas as pd
import os
import numpy as np
import re

# Phase 5 - Step 3: Perform QC and normalization per study
# This script normalizes S1, S2, and S3 using row-wise Z-score.
# It also renames S1 columns to follow the format: Y1.. (Young), C1.. (Control), A1.. (Case).

def create_qc_report(study_id, expr_file, meta_file, out_qc_file):
    """
    Create a QC report with sample-level and gene-level statistics.
    """
    print(f"  Creating QC report for {study_id}...")

    # Load raw expression data
    df = pd.read_csv(expr_file, sep="\t", index_col=0)

    # Load metadata
    df_meta = pd.read_csv(meta_file, sep="\t")

    # Get sample columns (exclude non-sample columns)
    sample_cols = [c for c in df.columns if "vs" not in c.lower() and c not in ["GeneID", "GeneSymbol"]]
    df_expr = df[sample_cols]

    # Calculate sample-level statistics
    sample_stats = []
    for col in sample_cols:
        values = pd.to_numeric(df_expr[col], errors='coerce').dropna()
        sample_stats.append({
            "sample_id": col,
            "total_counts": values.sum(),
            "mean_expression": values.mean(),
            "median_expression": values.median(),
            "std_expression": values.std(),
            "min_expression": values.min(),
            "max_expression": values.max(),
            "zero_count": (values == 0).sum(),
            "zero_percent": (values == 0).sum() / len(values) * 100,
            "detected_genes": (values > 0).sum()
        })
    df_sample_qc = pd.DataFrame(sample_stats)

    # Calculate gene-level statistics
    gene_stats = []
    for gene in df_expr.index:
        values = pd.to_numeric(df_expr.loc[gene], errors='coerce').dropna()
        gene_stats.append({
            "gene_id": gene,
            "mean_expression": values.mean(),
            "median_expression": values.median(),
            "std_expression": values.std(),
            "variance": values.var(),
            "cv": values.std() / values.mean() if values.mean() > 0 else 0,
            "zero_count": (values == 0).sum(),
            "detected_samples": (values > 0).sum()
        })
    df_gene_qc = pd.DataFrame(gene_stats)

    # Calculate summary statistics
    n_samples = len(sample_cols)
    n_genes = len(df_expr.index)
    n_genes_var = (df_expr.std(axis=1) > 0).sum()
    total_counts = df_sample_qc["total_counts"].sum()
    mean_counts_per_sample = df_sample_qc["total_counts"].mean()
    median_counts_per_sample = df_sample_qc["total_counts"].median()
    mean_detected_genes = df_sample_qc["detected_genes"].mean()
    mean_zero_percent = df_sample_qc["zero_percent"].mean()

    # Get condition breakdown from meta
    condition_counts = df_meta["characteristics_ch1"].apply(
        lambda x: "AD" if ("Aged, diseased" in str(x) or "Alzheimer" in str(x)) else "Control"
    ).value_counts().to_dict()

    # Create summary report
    summary = {
        "study_id": study_id,
        "n_samples": n_samples,
        "n_samples_AD": condition_counts.get("AD", 0),
        "n_samples_Control": condition_counts.get("Control", 0),
        "n_genes_total": n_genes,
        "n_genes_variable": n_genes_var,
        "total_raw_counts": int(total_counts),
        "mean_counts_per_sample": f"{mean_counts_per_sample:.2f}",
        "median_counts_per_sample": f"{median_counts_per_sample:.2f}",
        "mean_detected_genes_per_sample": f"{mean_detected_genes:.2f}",
        "mean_zero_percent": f"{mean_zero_percent:.2f}"
    }

    # Write QC report
    os.makedirs(os.path.dirname(out_qc_file), exist_ok=True)
    with open(out_qc_file, "w") as f:
        f.write("# QC Report for " + study_id + "\n")
        f.write("# Generated by step3_normalization.py\n\n")

        f.write("## Summary Statistics\n")
        for key, value in summary.items():
            f.write(f"{key}: {value}\n")

        f.write("\n## Sample-level QC Metrics\n")
        df_sample_qc.to_csv(f, sep="\t", index=False)

        f.write("\n## Gene-level QC Metrics (first 1000 genes)\n")
        df_gene_qc.head(1000).to_csv(f, sep="\t", index=False)

    print(f"  Saved QC report to {out_qc_file}")
    return summary


def create_meta_tsv(study_id, meta_file, out_meta_file):
    """
    Create a simplified meta.tsv with sample_id and condition columns.
    Condition is mapped to 'AD' or 'Control' based on study-specific characteristics.
    """
    print(f"  Creating meta.tsv for {study_id}...")
    
    df_meta = pd.read_csv(meta_file, sep="\t")
    
    if study_id == "S1":
        # Map based on characteristics_ch1: Young/Old -> Control, Aged, diseased -> AD
        records = []
        for _, row in df_meta.iterrows():
            # Keep .RNA suffix to match count matrix column names
            sample_id = row["title"].replace(".RNA.Young", ".RNA").replace(".RNA.Old", ".RNA").replace(".RNA.AD", ".RNA")
            char = row.get("characteristics_ch1", "")
            if "Aged, diseased" in char:
                condition = "AD"
            else:  # Young or Old
                condition = "Control"
            records.append({"sample_id": sample_id, "condition": condition})
        meta_out = pd.DataFrame(records)
        
    elif study_id == "S2":
        # Map based on characteristics_ch1: control -> Control, Alzheimer's -> AD
        # Column names in expression matrix are C1, C2... (Control) and A9, A10... (AD)
        records = []
        for _, row in df_meta.iterrows():
            gsm_id = row["sample_id"]
            char = row.get("characteristics_ch1", "").lower()
            if "control" in char:
                condition = "Control"
            elif "alzheimer" in char:
                condition = "AD"
            else:
                condition = "Unknown"
            # Map to the column names used in expression matrix (C1, C2, A9, A10, etc.)
            # Extract the sample number from title (e.g., RNAseq_Ctrl_1 -> C1, RNAseq_AD_9 -> A9)
            title = row.get("title", "")
            if "Ctrl" in title or "control" in char:
                match = re.search(r'Ctrl_(\d+)', title)
                if match:
                    sample_id = f"C{match.group(1)}"
                else:
                    sample_id = gsm_id
            elif "AD" in title:
                match = re.search(r'AD_(\d+)', title)
                if match:
                    sample_id = f"A{match.group(1)}"
                else:
                    sample_id = gsm_id
            else:
                sample_id = gsm_id
            records.append({"sample_id": sample_id, "condition": condition})
        meta_out = pd.DataFrame(records)
        
    elif study_id == "S3":
        # Map based on characteristics_ch1: control -> Control, Alzheimer's -> AD
        # Use GSM IDs directly as they appear in the count matrix
        records = []
        for _, row in df_meta.iterrows():
            sample_id = row["geo_accession"]
            char = row.get("characteristics_ch1", "").lower()
            if "control" in char:
                condition = "Control"
            elif "alzheimer" in char:
                condition = "AD"
            else:
                condition = "Unknown"
            records.append({"sample_id": sample_id, "condition": condition})
        meta_out = pd.DataFrame(records)
    
    # Save meta.tsv
    meta_out.to_csv(out_meta_file, sep="\t", index=False)
    print(f"  Saved meta.tsv to {out_meta_file} ({len(meta_out)} samples)")
    return meta_out


def normalize_study(study_id, expr_file, meta_file, out_file):
    """
    Implements Step 3: Normalization (z-score) row-wise.
    """
    print(f"--- Processing {study_id}: Normalization ---")
    
    # Check if expression file exists
    if not os.path.exists(expr_file):
        print(f"  [ERROR] {expr_file} not found. Skipping {study_id}.")
        return

    # Load the raw expression data (Ingested in Step 2)
    df = pd.read_csv(expr_file, sep="\t", index_col=0)
    
    # Load metadata for column mapping
    df_meta = pd.read_csv(meta_file, sep="\t")

    if study_id == "S1":
        # Task 2: Fix S1 column names to follow S2-like format (C1, A1, etc.)
        # Mapping S1: Young -> Y1, Old -> C1, Aged Diseased -> A1
        sample_cols = [c for c in df.columns if "vs" not in c.lower()]
        df = df[sample_cols]
        
        # Build mapping from current title-based column names to clean IDs
        new_cols = []
        y_count, c_count, a_count = 1, 1, 1
        for col in df.columns:
            # Map using metadata "title" column
            row = df_meta[df_meta["title"].str.contains(col, na=False)]
            char = row["characteristics_ch1"].values[0] if not row.empty else "Other"
            if "Young" in char:
                new_cols.append(f"Y{y_count}"); y_count += 1
            elif "study group: Old" in char:
                new_cols.append(f"C{c_count}"); c_count += 1
            elif "Aged, diseased" in char:
                new_cols.append(f"A{a_count}"); a_count += 1
            else:
                new_cols.append(f"X{col}")
        
        df.columns = new_cols
        print(f"  S1: Renamed columns to follow Y/C/A pattern.")

    elif study_id == "S2":
        # Cleaning S2: Use GeneSymbol as index and select RPKM columns.
        if "GeneSymbol" in df.columns:
            df = df.set_index("GeneSymbol")
        rpkm_cols = [c for c in df.columns if "_rpkm" in c]
        df = df[rpkm_cols]
        df.columns = [c.replace("_rpkm", "") for c in df.columns]

    elif study_id == "S3":
        # Rename S3 columns: Alzheimer -> A1, Control -> C1
        new_cols = []
        a_count, c_count = 1, 1
        for col in df.columns:
            # col is GSM ID
            row = df_meta[df_meta["geo_accession"] == col]
            char = row["characteristics_ch1"].values[0] if not row.empty else ""
            if "Alzheimer" in char:
                new_cols.append(f"A{a_count}"); a_count += 1
            elif "control" in char.lower() or "normal" in char.lower():
                new_cols.append(f"C{c_count}"); c_count += 1
            else:
                new_cols.append(f"X{col}")
        df.columns = new_cols
        print(f"  S3: Renamed columns to follow C/A pattern.")

    # Step 3 sub-step: Row-wise (Gene-wise) Z-score normalization
    # Remove genes with zero variance
    initial_count = len(df)
    df = df[df.std(axis=1) > 0]
    if len(df) < initial_count:
        print(f"  Removed {initial_count - len(df)} genes with zero variance.")

    # Apply row-wise Z-score: (x - mean) / std
    normalized_df = df.apply(lambda x: (x - x.mean()) / x.std(), axis=1)
    
    # Step 3 output: Save normalized matrix
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    normalized_df.to_csv(out_file, sep="\t")
    print(f"  Step 3 Complete: Saved to {out_file} (Shape: {normalized_df.shape})\n")

# Create meta.tsv files for S1, S2, S3
create_meta_tsv("S1", "results/transcriptome/S1/metadata.tsv", "results/transcriptome/S1/meta.tsv")
create_meta_tsv("S2", "results/transcriptome/S2/metadata.tsv", "results/transcriptome/S2/meta.tsv")
create_meta_tsv("S3", "results/transcriptome/S3/metadata.tsv", "results/transcriptome/S3/meta.tsv")

# Create QC reports for S1, S2, S3
create_qc_report("S1", "results/transcriptome/S1/expression_raw.tsv", "results/transcriptome/S1/metadata.tsv", "results/transcriptome/S1/qc_report.txt")
create_qc_report("S2", "results/transcriptome/S2/expression_raw.tsv", "results/transcriptome/S2/metadata.tsv", "results/transcriptome/S2/qc_report.txt")
create_qc_report("S3", "results/transcriptome/S3/expression_raw.tsv", "results/transcriptome/S3/metadata.tsv", "results/transcriptome/S3/qc_report.txt")

# Execute normalization for S1, S2, and S3
normalize_study("S1", "results/transcriptome/S1/expression_raw.tsv", "results/transcriptome/S1/metadata.tsv", "results/transcriptome/S1/expression_normalized.tsv")
normalize_study("S2", "results/transcriptome/S2/expression_raw.tsv", "results/transcriptome/S2/metadata.tsv", "results/transcriptome/S2/expression_normalized.tsv")
normalize_study("S3", "results/transcriptome/S3/expression_raw.tsv", "results/transcriptome/S3/metadata.tsv", "results/transcriptome/S3/expression_normalized.tsv")
